modLoader="javafml"
loaderVersion="[33,)"
issueTrackerURL="https://github.com/CorgiTaco/UndergroundBiomesConstructs/issues"
license = "GPLv2"
[[mods]]
modId="undergroundbiomes"
version="${file.jarVersion}"
displayName="Underground Biomes"
logoFile="undergroundbiomes.png"
authors="exterminatorJeff, Zeno410, kyeiti, Kreezxi,\n Maintained by Corgi Taco"
description='''
24 new different kinds of stones with slabs, stairs, walls, and buttons!
'''

[[dependencies.undergroundbiomes]]
modId = "forge"
mandatory = true
versionRange = "[34.0.0,)"
ordering = "NONE"
side = "BOTH"